apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: zero-hotel-tidb
  namespace: zero-cloud-hotel
spec:
  image: tnir/mysqlclient
  # imagePullPolicy: IfNotPresent
  cluster:
    namespace: zero-cloud-hotel
    name: zero-hotel-tidb
  initSql:
    # create database app;
    # initSqlConfigMap: tidb-initsql
  passwordSecret: tidb-secret
  # permitHost: 172.6.5.8
  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 500Mi
  #   requests:
  #     cpu: 100m
  #     memory: 50Mi
  # timezone: "Asia/Shanghai"